spring.application.name=microservicio-java

server.port=${PORT:8080}
server.address=0.0.0.0

# Cargar variables desde .env local
spring.config.import=optional:file:.env[.properties]

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# No modificar la estructura existente de la BD
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html